---

# Generate the definition from the kustomize sources
- name: Create temporary area
  ansible.builtin.tempfile:
    state: directory
  register: temp_dir
  check_mode: false
  delegate_to: localhost

- name: Generate kustomize definition
  delegate_to: localhost
  block:
    - name: Copy sources
      copy:
        src: "{{ item }}"
        dest: "{{ temp_dir.path }}"
      check_mode: false
      loop: "{{ kustomize_sources }}"

    - name: set overlay path
      set_fact:
        kustomize_overlay_path: "{{ temp_dir.path }}/{{ kustomize_overlay_name }}"

    - name: Generate definition
      set_fact:
        kustomize_definition: "{{ lookup('kubernetes.core.kustomize', dir=kustomize_overlay_path) }}"
  always:
    - name: Remove temporary directory
      file:
        path: "{{ temp_dir.path }}"
        state: absent
      check_mode: false

- name: Apply manifest
  kubernetes.core.k8s:
    apply: true
    definition: "{{ kustomize_definition }}"
    kubeconfig: "{{ kustomize_kubeconfig }}"
    no_proxy: true
  delegate_to: "{{ kustomize_delegation }}"
  register: kustomize_apply_result

- name: Apply result
  debug:
    msg: "{{ kustomize_apply_result | to_yaml(indent=4) | split('\n') }}"
